# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atuadores_def.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61tuadores_def.proto\"\x1c\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x05\"6\n\x0eSprinklerReply\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x15\n\rmanual_action\x18\x02 \x01(\x08\"\x1a\n\tLightness\x12\r\n\x05value\x18\x01 \x01(\x02\"H\n\tLampReply\x12\r\n\x05is_on\x18\x01 \x01(\x08\x12\x15\n\rmanual_action\x18\x02 \x01(\x08\x12\x15\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x06.Color\"\x16\n\x05\x43olor\x12\r\n\x05\x63olor\x18\x01 \x01(\t\"\x1d\n\x0cRainPresence\x12\r\n\x05value\x18\x01 \x01(\x08\"\'\n\x14RetractableRoofReply\x12\x0f\n\x07is_open\x18\x01 \x01(\x08\"\x06\n\x04Void2\x8e\x01\n\tSprinkler\x12)\n\x06Notify\x12\x0c.Temperature\x1a\x0f.SprinklerReply\"\x00\x12)\n\rActivateAlarm\x12\x05.Void\x1a\x0f.SprinklerReply\"\x00\x12+\n\x0f\x44\x65\x61\x63tivateAlarm\x12\x05.Void\x1a\x0f.SprinklerReply\"\x00\x32\x8e\x01\n\x04Lamp\x12\"\n\x06Notify\x12\n.Lightness\x1a\n.LampReply\"\x00\x12\x1d\n\x06TurnOn\x12\x05.Void\x1a\n.LampReply\"\x00\x12\x1e\n\x07TurnOff\x12\x05.Void\x1a\n.LampReply\"\x00\x12#\n\x0b\x43hangeColor\x12\x06.Color\x1a\n.LampReply\"\x00\x32\x94\x01\n\x0fRetractableRoof\x12\x30\n\x06Notify\x12\r.RainPresence\x1a\x15.RetractableRoofReply\"\x00\x12&\n\x04Open\x12\x05.Void\x1a\x15.RetractableRoofReply\"\x00\x12\'\n\x05\x43lose\x12\x05.Void\x1a\x15.RetractableRoofReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atuadores_def_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPERATURE._serialized_start=23
  _TEMPERATURE._serialized_end=51
  _SPRINKLERREPLY._serialized_start=53
  _SPRINKLERREPLY._serialized_end=107
  _LIGHTNESS._serialized_start=109
  _LIGHTNESS._serialized_end=135
  _LAMPREPLY._serialized_start=137
  _LAMPREPLY._serialized_end=209
  _COLOR._serialized_start=211
  _COLOR._serialized_end=233
  _RAINPRESENCE._serialized_start=235
  _RAINPRESENCE._serialized_end=264
  _RETRACTABLEROOFREPLY._serialized_start=266
  _RETRACTABLEROOFREPLY._serialized_end=305
  _VOID._serialized_start=307
  _VOID._serialized_end=313
  _SPRINKLER._serialized_start=316
  _SPRINKLER._serialized_end=458
  _LAMP._serialized_start=461
  _LAMP._serialized_end=603
  _RETRACTABLEROOF._serialized_start=606
  _RETRACTABLEROOF._serialized_end=754
# @@protoc_insertion_point(module_scope)
